name: CI

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - utils/**
      - zappa_settings.json
      - run.py
  pull_request:
    branches:
      - main
    paths:
      - api/**
      - utils/**
      - zappa_settings.json
      - run.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Check python version
        run: python --version
