name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v1
        with:
          path: venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }} 

      - name: Install Requirements
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: | 
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Zappa deployment
        run: |
          source venv/bin/activate
          zappa update -s gh_zappa_settings.json dev
